import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import useBearStore from "../zustand/store";

import { signIn, useSession } from "next-auth/react"

const Home: NextPage = () => {


  const session = useSession()

 
 

  return (
    <>
      <Head>
        <title>BOXEDD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Link className="link1" href={'/dashboard'}>dashboard</Link>
        <p onClick={()=>signIn()}>login</p>

    </>
  );
};

export default Home;


